/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ytripper;

import com.ytripper.net.YoutubeConnection;
import com.ytripper.thread.YoutubeDownloadJob;
import com.ytripper.thread.YoutubeDownloadThreadPool;
import com.ytripper.video.YoutubePlaylistObject;
import com.ytripper.video.YoutubeVideoObject;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author mmain
 */
public class YoutubeRipperFrame extends javax.swing.JFrame {
    YoutubeDownloadThreadPool pool = new YoutubeDownloadThreadPool();
    ArrayList<YoutubeDownloadJob> runningTasks = new ArrayList<>();
    
    private Timer timer;
    
    /**
     * Creates new form YoutubeRipperFrame
     */
    public YoutubeRipperFrame() {
        initComponents();
        timer = new Timer(40, new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e) {
                runningTasksList.setListData(runningTasks.toArray());
            }
        });
        
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        youtubeUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        playlistId = new javax.swing.JTextField();
        downloadOneButton = new javax.swing.JButton();
        downloadPlaylistButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        runningTasksList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deus the Ripper (YouTube Ripping Tool)");

        jLabel1.setText("Youtube URL");

        jLabel2.setText("Youtube Playlist ID");

        downloadOneButton.setText("Download Single Video");
        downloadOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadOneButtonActionPerformed(evt);
            }
        });

        downloadPlaylistButton.setText("Download Playlist");
        downloadPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadPlaylistButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(runningTasksList);

        jLabel3.setText("Running Tasks:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(youtubeUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .addComponent(playlistId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(downloadOneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downloadPlaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youtubeUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(downloadOneButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(playlistId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadPlaylistButton))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadOneButtonActionPerformed
        YoutubeVideoObject video = YoutubeConnection.getYoutubeVideoObject(youtubeUrl.getText());
        
        YoutubeDownloadJob job = new YoutubeDownloadJob(video, 720, "mp4", "E:/media/Youtube/singles");
        pool.addJob(job);
        runningTasks.add(job);
        
        youtubeUrl.setText("");
        runningTasksList.setListData(runningTasks.toArray());
    }//GEN-LAST:event_downloadOneButtonActionPerformed

    private void downloadPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadPlaylistButtonActionPerformed
        YoutubePlaylistObject playlist = YoutubeConnection.getYoutubePlaylistObject(playlistId.getText());
        
        for (YoutubeVideoObject video : playlist.getYoutubeVideoObjects()) {
            YoutubeDownloadJob job = new YoutubeDownloadJob(video, 720, "mp4", "E:/media/Youtube/" + playlist.getSafeTitle());
            pool.addJob(job);
            runningTasks.add(job);
        }
        
        playlistId.setText("");
        runningTasksList.setListData(runningTasks.toArray());
    }//GEN-LAST:event_downloadPlaylistButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadOneButton;
    private javax.swing.JButton downloadPlaylistButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField playlistId;
    private javax.swing.JList runningTasksList;
    private javax.swing.JTextField youtubeUrl;
    // End of variables declaration//GEN-END:variables
}
